/*
 * This source file was generated by the Gradle 'init' task
 */
package _CheckersUnitTesting;

import org.junit.jupiter.api.Test;

import com.game.core.Controller;
import com.game.entities.Player;
import com.game.logic.Move;
import com.game.objects.Board;
import com.game.objects.BoardSquare;
import com.game.objects.Checker;
import com.game.ui.BoardUI;
import com.game.util.GameException;

import javafx.scene.layout.Pane;

import static org.junit.jupiter.api.Assertions.*;

class UnitTests {
    @Test void test1() {
        Checker checker = new Checker("Black", false, 0, 0);
        assertFalse(checker.isKing(), "isKing should return 'false'");
    }
    
    @Test void test2() {
        Checker checker = new Checker("Black", false, 0, 0);
        checker.setCheckerKing();
        assertTrue(checker.isKing(), "isKing should return 'true'");
    }
    
    @Test void test3() {
        Checker checker = new Checker("Black", false, 0, 0);
        assertEquals("Black", checker.getColor(), "getColor should return 'Black'");
    }
    
    @Test void test4() {
        Board board = new Board();
        board.newGame();
        Checker[][] checkerBoard = Board.getCheckers();
        int blackPieces = 0;
        int redPieces = 0;
        
        // Count pieces on the board
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                if (checkerBoard[i][j] != null) {
                    if (checkerBoard[i][j].getColor().equals("Black")) {
                        blackPieces++;
                    } else if (checkerBoard[i][j].getColor().equals("Red")) {
                        redPieces++;
                    }
                }
            }
        }
       
        assertTrue(blackPieces == 12 && redPieces == 12,"newGame should populate its board with 12 Black checkers and 12 Red checkers.");
    }
    
    @Test void test5() {
        Board board = new Board();
        
        board.newGame();
        board.clearPosition(0, 0, false);
        Checker[][] checkerBoard = Board.getCheckers();
        assertNull( checkerBoard[0][0], "clearPosition should remove a checker from board at position checekrBoard[0][0]");
    }
    
    @Test void test6() {
    	Board board = new Board();
    	Checker[][] checkerBoard;
    	
    	board.newGame();
    	checkerBoard = Board.getCheckers();
    	board.promoteToKing(0, 0);
    	
        assertTrue(checkerBoard[0][0].isKing(), "promoteToKing should modify the checker at checkerBoard[0]][0] and isKing should return 'true'");
    }
    
    @Test void test7() {
    	Board board = new Board();
    	board.newGame();
    	Checker[][] checker = Board.getCheckers();
    	
    	Pane pane = new Pane();
    	
    	BoardUI boardUI = new BoardUI(pane, board);
    	BoardSquare bsq = new BoardSquare("Black", 1, 1);
    	Move move = new Move(board, boardUI);
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.makeMove(checker[0][0], bsq),
    			"Expected makeMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("Destination square is already occupied."), "makeMove should return a GameException with message 'You must choose an empty spot.'");
    }
    
    @Test void test8() {
    	Board board = new Board();
    	board.newGame();
    	Checker[][] checker = Board.getCheckers();
    	
    	Pane pane = new Pane();
    	
    	BoardUI boardUI = new BoardUI(pane, board);
    	BoardSquare bsq = new BoardSquare("Black", 4, 4);
    	Controller.player1Turn = true;
    	Move move = new Move(board, boardUI);
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.makeMove(Board.getCheckers()[6][6], bsq),
    			"Expected makeMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("Cannot capture your own piece."), "makeMove should return a GameException with message 'Cannot capture your own piece.'\n" + thrown.getMessage());
    	
    }
    
    @Test void test9() {
    	Board board = new Board();
    	board.newGame();
    	Checker[][] checker = Board.getCheckers();
    	
    	Pane pane = new Pane();
    	
    	BoardUI boardUI = new BoardUI(pane, board);
    	BoardSquare bsq = new BoardSquare("Black", 3, 3);
    	Controller.player1Turn = true;
    	Move move = new Move(board, boardUI);
    	Player player = new Player("player", "Black", true);
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.makeMove(checker[6][6], bsq),
    			"Expected makeMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("Pieces can only move one to two spaces diagonally."), 
    			"makeMove should return a GameException with message 'Pieces can only move one to two spaces diagonally.'");
    }
    
    @Test void test10() {
    	Board board = new Board();
    	board.newGame();
    	Checker[][] checker = Board.getCheckers();
    	
    	Pane pane = new Pane();
    	
    	BoardUI boardUI = new BoardUI(pane, board);
    	BoardSquare bsq = new BoardSquare("Black", 6, 7);
    	Controller.player1Turn = true;
    	Move move = new Move(board, boardUI);
    	Player player = new Player("player", "Black", true);
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.makeMove(checker[6][6], bsq),
    			"Expected makeMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("Pieces can only move one to two spaces diagonally"), 
    			"makeMove should return a GameException with message 'Pieces can only move one to two spaces diagonally'");
    }
    
    @Test void test11() {
    	Board board = new Board();
    	board.newGame();
    	Checker[][] checker = Board.getCheckers();
    	
    	Pane pane = new Pane();
    	
    	BoardUI boardUI = new BoardUI(pane, board);
    	BoardSquare bsq = new BoardSquare("Black", 5, 6);
    	Controller.player1Turn = true;
    	Move move = new Move(board, boardUI);
    	Player player = new Player("player", "Black", true);
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.makeMove(checker[6][6], bsq),
    			"Expected makeMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("Invalid move. You must move your pieces diagonally."), 
    			"makeMove should return a GameException with message 'Invalid move. You must move your pieces diagonally.'");
    }
    
    @Test void test12() {
    	Board board = new Board();
    	board.newGame();
    	Checker[][] checker = Board.getCheckers();
    	
    	Pane pane = new Pane();
    	
    	BoardUI boardUI = new BoardUI(pane, board);
    	BoardSquare bsq = new BoardSquare("Black", -1, 9);
    	Controller.player1Turn = true;
    	Move move = new Move(board, boardUI);
    	Player player = new Player("player", "Black", true);
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.makeMove(checker[0][0], bsq),
    			"Expected makeMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("Invalid move to -1, 9. You must move your piece within the game board"), 
    			"makeMove should return a GameException with message 'Invalid move to -1, 9. You must move your piece within the game board'");
    }
    
    @Test void test13() {
    	Board board = new Board();
    	board.newGame();
    	Checker[][] checker = Board.getCheckers();
    	
    	Pane pane = new Pane();
    	
    	BoardUI boardUI = new BoardUI(pane, board);
    	BoardSquare bsq = new BoardSquare("Black", 1, 2);
    	Controller.player1Turn = true;
    	Move move = new Move(board, boardUI);
    	Player player = new Player("player", "Black", true);
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.makeMove(checker[0][1], bsq),
    			"Expected makeMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("You did not select a Checker. Please select a Checker."), 
    			"makeMove should return a GameException with message 'You did not select a Checker. Please select a Checker.'");
    }
    
    @Test void test14() {
    	Board board = new Board();
    	board.newGame();
    	Checker[][] checker = Board.getCheckers();
    	
    	Pane pane = new Pane();
    	
    	BoardUI boardUI = new BoardUI(pane, board);
    	BoardSquare bsq = new BoardSquare("Black", 3, 5);
    	Controller.player1Turn = true;
    	Move move = new Move(board, boardUI);
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.makeMove(checker[5][7], bsq),
    			"Expected makeMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("Invalid capture move. No piece to capture at 4, 6"), 
    			"makeMove should return a GameException with message 'Invalid capture move. No piece to capture at 4, 6'");
    }
    
    @Test void test15() {
    	Board board = new Board();
    	board.newGame();
    	Checker[][] checker = Board.getCheckers();
    	board.setBoard("Black", false, 4, 0, checker);
    	
    	Pane pane = new Pane();
    	
    	BoardUI boardUI = new BoardUI(pane, board);
    	BoardSquare bsq = new BoardSquare("Black", 3, 1);
    	Controller.player1Turn = false;
    	Move move = new Move(board, boardUI);
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.makeMove(checker[4][0], bsq),
    			"Expected makeMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("Invalid move. Non-Kinged Black pieces can only move down the board."), 
    			"makeMove should return a GameException with message 'Invalid move. Non-Kinged Red pieces can only move down the board.'");
    }
}