/*
 * This source file was generated by the Gradle 'init' task
 */
package _CheckersUnitTesting;

import org.junit.jupiter.api.Test;

import com.game.entities.Player;
import com.game.logic.Move;
import com.game.objects.Board;
import com.game.objects.Checker;
import com.game.util.GameException;

import static org.junit.jupiter.api.Assertions.*;

class UnitTests {
    @Test void test1() {
        Checker checker = new Checker("Black", false);
        assertFalse(checker.isKing(), "isKing should return 'false'");
    }
    
    @Test void test2() {
        Checker checker = new Checker("Black", false);
        checker.setCheckerKing();
        assertTrue(checker.isKing(), "isKing should return 'true'");
    }
    
    @Test void test3() {
        Checker checker = new Checker("Black", false);
        assertEquals("Black", checker.getColor(), "getColor should return 'Black'");
    }
    
    @Test void test4() {
        Board board = new Board();
        board.newGame();
        Checker[][] checkerBoard = board.getBoard();
        int blackPieces = 0;
        int redPieces = 0;
        
        // Count pieces on the board
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                if (checkerBoard[i][j] != null) {
                    if (checkerBoard[i][j].getColor().equals("Black")) {
                        blackPieces++;
                    } else if (checkerBoard[i][j].getColor().equals("Red")) {
                        redPieces++;
                    }
                }
            }
        }
        
        
        
        board.newGame();
        assertTrue(blackPieces == 12 && redPieces == 12,"newGame should populate its board with 12 Black checkers and 12 Red checkers.");
    }
    
    @Test void test5() {
        Board board = new Board();
        
        board.newGame();
        board.clearPosition(0, 0);
        Checker[][] checkerBoard = board.getBoard();
        assertNull( checkerBoard[0][0], "clearPosition should remove a checker from board at position checekrBoard[0][0]");
    }
    
    @Test void test6() {
    	Board board = new Board();
    	Checker[][] checkerBoard;
    	
    	board.newGame();
    	checkerBoard = board.getBoard();
    	board.promoteToKing(0, 0);
    	
        assertTrue(checkerBoard[0][0].isKing(), "promoteToKing should modify the checker at checkerBoard[0]][0] and isKing should return 'true'");
    }
    
    @Test void test7() {
    	Board board = new Board();
    	board.newGame();
    	Move move = new Move(0,0,1,1);
    	Player player = new Player("player", "Black");
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.validateMove(board, player),
    			"Expected validateMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("You must choose an empty spot."), "validateMove should return a GameException with message 'You must choose an empty spot.'");
    }
    
    @Test void test8() {
    	Board board = new Board();
    	board.newGame();
    	Move move = new Move(1,1,3,3);
    	Player player = new Player("player", "Black");
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.validateMove(board, player),
    			"Expected validateMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("Cannot capture your own piece."), "validateMove should return a GameException with message 'Cannot capture your own piece.'");
    }
    
    @Test void test9() {
    	Board board = new Board();
    	board.newGame();
    	Move move = new Move(0,0,4,4);
    	Player player = new Player("player", "Black");
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.validateMove(board, player),
    			"Expected validateMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("Pieces can only move one to two spaces diagonally."), 
    			"validateMove should return a GameException with message 'Pieces can only move one to two spaces diagonally.'");
    }
    
    @Test void test10() {
    	Board board = new Board();
    	board.newGame();
    	Move move = new Move(0,0,0,1);
    	Player player = new Player("player", "Black");
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.validateMove(board, player),
    			"Expected validateMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("Invalid move. You must move your pieces diagonally."), 
    			"validateMove should return a GameException with message 'Invalid move. You must move your pieces diagonally.'");
    }
    
    @Test void test11() {
    	Board board = new Board();
    	board.newGame();
    	Move move = new Move(0,0,1,0);
    	Player player = new Player("player", "Black");
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.validateMove(board, player),
    			"Expected validateMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("Invalid move. You must move your pieces diagonally."), 
    			"validateMove should return a GameException with message 'Invalid move. You must move your pieces diagonally.'");
    }
    
    @Test void test12() {
    	Board board = new Board();
    	board.newGame();
    	Move move = new Move(0,0,-1,9);
    	Player player = new Player("player", "Black");
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.validateMove(board, player),
    			"Expected validateMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("Invalid move to -1, 9. You must move your piece within the game board"), 
    			"validateMove should return a GameException with message 'Invalid move to -1, 9. You must move your piece within the game board'");
    }
    
    @Test void test13() {
    	Board board = new Board();
    	board.newGame();
    	Move move = new Move(0,1,0,0);
    	Player player = new Player("player", "Black");
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.validateMove(board, player),
    			"Expected validateMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("You did not select a Checker. Please select a Checker."), 
    			"validateMove should return a GameException with message 'You did not select a Checker. Please select a Checker.'");
    }
    
    @Test void test14() {
    	Board board = new Board();
    	board.newGame();
    	Move move = new Move(2,0,4,2);
    	Player player = new Player("player", "Black");
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.validateMove(board, player),
    			"Expected validateMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("Invalid capture move. No piece to capture at 3, 1"), 
    			"validateMove should return a GameException with message 'Invalid capture move. No piece to capture at 3, 1'");
    }
    
    @Test void test15() {
    	Board board = new Board();
    	board.newGame();
    	Player player = new Player("player", "Black");
    	
    	board.setBoard("Black", false, 4, 6, board.getBoard());
    	Move move = new Move(4,6,3,7);
    	
    	GameException thrown = assertThrows(
    			GameException.class,
    			() -> move.validateMove(board, player),
    			"Expected validateMove() to throw a GameException, but didn't"
    			);
    	
    	assertTrue(thrown.getMessage().contains("Invalid move. Non-Kinged Black pieces can only move down the board."), 
    			"validateMove should return a GameException with message 'Invalid move. Non-Kinged Black pieces can only move down the board.'");
    }
    
    @Test void test16() {
    	Board board = new Board();
    	board.newGame();
    	Player player = new Player("player", "Black");
    	boolean success = false;
    	
    	board.setBoard("Red", false, 3, 1, board.getBoard());
    	Move move = new Move(2,0,4,2);
    	
    	try {
    		move.validateMove(board, player);
    		success = true;
    	} catch(GameException gE) {
    		success = false;
    	}
    	
    	assertTrue(success);
    }
    
    @Test void test17() {
    	Board board = new Board();
    	board.newGame();
    	Player player = new Player("player", "Black");
    	boolean success = false;
    	Move move = new Move(2,2,3,3);
    	
    	try {
    		move.validateMove(board, player);
    		success = true;
    	} catch(GameException gE) {
    		success = false;
    	}
    	
    	assertTrue(success);
    }
}